version: '2'

services:
  rollweb:
    build: .
    command: >
      gunicorn -b 0.0.0.0:5000
        --access-logfile -
        --reload
        "rolldice.app:create_app()"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/rolldice'
    ports:
      - '5000:5000'
