version: '2'

services:
  redis:
    image: 'redis:3.0-alpine'
    command: redis-server --requirepass devpassword
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
        -  '6379:6379'

  rollweb:
    build: .
    command: >
      gunicorn -b 0.0.0.0:5000
        --access-logfile -
        --reload
        "rolldice.app:create_app()"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/rolldice'
    ports:
      - '5000:5000'

  celery:
    build: .
    command: celery worker -l info -A rolldice.blueprints.contact.tasks
    env_file:
      - '.env'
    volumes:
      - '.:/rolldice'

volumes:
  redis: